/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MySidebar {
        "title": string;
    }
    interface MyTooltip {
        "text": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMySidebarElement extends Components.MySidebar, HTMLStencilElement {
    }
    var HTMLMySidebarElement: {
        prototype: HTMLMySidebarElement;
        new (): HTMLMySidebarElement;
    };
    interface HTMLMyTooltipElement extends Components.MyTooltip, HTMLStencilElement {
    }
    var HTMLMyTooltipElement: {
        prototype: HTMLMyTooltipElement;
        new (): HTMLMyTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-sidebar": HTMLMySidebarElement;
        "my-tooltip": HTMLMyTooltipElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MySidebar {
        "title"?: string;
    }
    interface MyTooltip {
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-sidebar": MySidebar;
        "my-tooltip": MyTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-sidebar": LocalJSX.MySidebar & JSXBase.HTMLAttributes<HTMLMySidebarElement>;
            "my-tooltip": LocalJSX.MyTooltip & JSXBase.HTMLAttributes<HTMLMyTooltipElement>;
        }
    }
}
